github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: juancarlospaco # Replace with a single Patreon username
liberapay: juancarlospaco # Replace with a single Liberapay username
custom: ["https://streamlabs.com/juancarlospaco", "http://mpago.la/mhzi"] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
